2022-05-30 13:57:24 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-30 13:59:27 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-30 14:15:16 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-30 14:36:13 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-30 16:00:28 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-30 16:07:14 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-30 16:08:21 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectLastExecutions(ExecutionDataDB.java:149)
	at com.indra.cilantrum.report.listeners.CilantrumReporter.generateReport(CilantrumReporter.java:96)
	at org.testng.TestNG.generateReports(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:1005)
	at com.indra.cilantrum.framework.build.Build.execute(Build.java:118)
	at com.indra.cilantrum.framework.main.Main.executeBuild(Main.java:254)
	at com.indra.cilantrum.framework.main.Main.main(Main.java:72)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:104)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 36 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 30 more
2022-05-30 16:08:21 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.saveExecutionResult(ExecutionDataDB.java:48)
	at com.indra.cilantrum.report.listeners.CilantrumReporter.saveResults(CilantrumReporter.java:266)
	at com.indra.cilantrum.report.listeners.CilantrumReporter.generateReport(CilantrumReporter.java:117)
	at org.testng.TestNG.generateReports(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:1005)
	at com.indra.cilantrum.framework.build.Build.execute(Build.java:118)
	at com.indra.cilantrum.framework.main.Main.executeBuild(Main.java:254)
	at com.indra.cilantrum.framework.main.Main.main(Main.java:72)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:104)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 37 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 31 more
2022-05-31 09:46:26 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-31 10:53:21 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-31 11:47:47 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-31 12:17:26 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-31 12:29:08 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-31 13:25:00 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-31 13:35:06 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-05-31 16:00:32 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-01 16:29:35 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectLastExecutions(ExecutionDataDB.java:149)
	at com.indra.cilantrum.report.listeners.CilantrumReporter.generateReport(CilantrumReporter.java:96)
	at org.testng.TestNG.generateReports(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:1005)
	at com.indra.cilantrum.framework.build.Build.execute(Build.java:118)
	at com.indra.cilantrum.framework.main.Main.executeBuild(Main.java:254)
	at com.indra.cilantrum.framework.main.Main.main(Main.java:72)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:104)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 36 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 30 more
2022-06-01 16:29:35 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.saveExecutionResult(ExecutionDataDB.java:48)
	at com.indra.cilantrum.report.listeners.CilantrumReporter.saveResults(CilantrumReporter.java:266)
	at com.indra.cilantrum.report.listeners.CilantrumReporter.generateReport(CilantrumReporter.java:117)
	at org.testng.TestNG.generateReports(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:1005)
	at com.indra.cilantrum.framework.build.Build.execute(Build.java:118)
	at com.indra.cilantrum.framework.main.Main.executeBuild(Main.java:254)
	at com.indra.cilantrum.framework.main.Main.main(Main.java:72)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:104)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 37 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 31 more
2022-06-01 16:29:36 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.prueba1.main(prueba1.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/eclipse-workspace/Curso_Cilantrum2020/3.-Ejercicios_Cilantrum/EjerciciosCilantrum/src/main/resources/results.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 25 more
2022-06-03 13:36:21 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-03 14:36:07 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-03 14:38:00 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-03 14:38:37 jdbc[6]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectLastExecutions(ExecutionDataDB.java:149)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:85)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 08:10:33 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 08:18:38 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 08:24:01 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 09:59:42 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 10:08:17 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 10:11:25 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 10:54:16 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 10:57:16 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 11:28:05 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 11:34:13 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 11:37:10 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 11:39:52 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 11:46:58 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 11:50:45 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.LaunchAmazon.main(LaunchAmazon.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-06 16:47:20 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ayuntamientoMadrid.main.LaunchAPIMadrid.main(LaunchAPIMadrid.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-07 08:04:14 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ayuntamientoMadrid.main.LaunchAPIMadrid.main(LaunchAPIMadrid.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-07 08:23:36 jdbc[5]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:83)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ayuntamientoMadrid.main.LaunchAPIMadrid.main(LaunchAPIMadrid.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-07 08:38:49 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ayuntamientoMadrid.main.LaunchAPIMadrid.main(LaunchAPIMadrid.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-07 09:24:58 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ayuntamientoMadrid.main.LaunchAPIMadrid.main(LaunchAPIMadrid.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-07 12:55:54 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ayuntamientoMadrid.main.LaunchAPIMadrid.main(LaunchAPIMadrid.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-14 12:55:07 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ejercicioVodafone.main.LaunchEjercicioVodafone.main(LaunchEjercicioVodafone.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-14 12:55:50 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ejercicioVodafone.main.LaunchEjercicioVodafone.main(LaunchEjercicioVodafone.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-14 12:56:24 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ejercicioVodafone.main.LaunchEjercicioVodafone.main(LaunchEjercicioVodafone.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2022-06-14 17:15:50 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectLastExecutions(ExecutionDataDB.java:149)
	at com.indra.cilantrum.report.listeners.CilantrumReporter.generateReport(CilantrumReporter.java:96)
	at org.testng.TestNG.generateReports(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:1005)
	at com.indra.cilantrum.framework.build.Build.execute(Build.java:118)
	at com.indra.cilantrum.framework.main.Main.executeBuild(Main.java:254)
	at com.indra.cilantrum.framework.main.Main.main(Main.java:72)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:104)
	at com.indra.main.ejercicioVodafone.main.LaunchEjercicioVodafone.main(LaunchEjercicioVodafone.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 36 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 30 more
2022-06-14 17:15:50 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.saveExecutionResult(ExecutionDataDB.java:48)
	at com.indra.cilantrum.report.listeners.CilantrumReporter.saveResults(CilantrumReporter.java:266)
	at com.indra.cilantrum.report.listeners.CilantrumReporter.generateReport(CilantrumReporter.java:117)
	at org.testng.TestNG.generateReports(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:1005)
	at com.indra.cilantrum.framework.build.Build.execute(Build.java:118)
	at com.indra.cilantrum.framework.main.Main.executeBuild(Main.java:254)
	at com.indra.cilantrum.framework.main.Main.main(Main.java:72)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:104)
	at com.indra.main.ejercicioVodafone.main.LaunchEjercicioVodafone.main(LaunchEjercicioVodafone.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 37 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 31 more
2022-06-14 17:15:51 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ejercicioVodafone.main.LaunchEjercicioVodafone.main(LaunchEjercicioVodafone.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 31 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/fjcastroe/git/EjercicioVodafone/EjercicioQAVodafone/src/main/resources/results.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 25 more
2022-06-16 09:24:00 jdbc[4]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at com.indra.cilantrum.report.api.db.h2.H2BD.connect(H2BD.java:34)
	at com.indra.cilantrum.report.api.db.CommonDB.<init>(CommonDB.java:26)
	at com.indra.cilantrum.report.api.db.h2.H2BD.<init>(H2BD.java:23)
	at com.indra.cilantrum.report.utils.db.ExecutionDataDB.selectAllData(ExecutionDataDB.java:85)
	at com.indra.cilantrum.report.filegen.CreateExecutionReporter.generateExecutionReport(CreateExecutionReporter.java:69)
	at com.indra.cilantrum.framework.main.Main.launchBuild(Main.java:125)
	at com.indra.main.ejercicioVodafone.main.LaunchEjercicio1_Cilantrum.main(LaunchEjercicio1_Cilantrum.java:12)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
